"""add booking table

Revision ID: 0677511dc2b9
Revises: b51b81b0bbbb
Create Date: 2025-06-23 20:46:50.543911

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0677511dc2b9'
down_revision = 'b51b81b0bbbb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookings',
    sa.Column('booking_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('charging_location_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.String(length=50), nullable=False),
    sa.Column('end_time', sa.String(length=50), nullable=False),
    sa.Column('review_rate', sa.Integer(), nullable=True),
    sa.Column('review_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['charging_location_id'], ['charging_locations.charging_location_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('booking_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('booking',
    sa.Column('booking_id', sa.INTEGER(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('charging_location_id', sa.INTEGER(), nullable=True),
    sa.Column('review_rate', sa.TEXT(), nullable=True),
    sa.Column('startDate', sa.TEXT(), nullable=True),
    sa.Column('endDate', sa.TEXT(), nullable=True),
    sa.Column('review_message', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('booking_id')
    )
    op.drop_table('bookings')
    # ### end Alembic commands ###
