"""update charging loc

Revision ID: fd551f97f924
Revises: 7910e2b92862
Create Date: 2025-07-20 13:50:54.937256

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd551f97f924'
down_revision = '7910e2b92862'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('charging_locations', sa.Column('lattitude', sa.Text(), nullable=True))
    op.add_column('charging_locations', sa.Column('longtitude', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('charging_locations', 'longtitude')
    op.drop_column('charging_locations', 'lattitude')
    # ### end Alembic commands ###
