"""drop some tbale

Revision ID: 420e5c313c30
Revises: 15cf224f16b0
Create Date: 2025-06-29 23:15:09.518202

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '420e5c313c30'
down_revision = '15cf224f16b0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notification')
    op.drop_table('booking')
    op.drop_table('review')
    op.drop_table('charging_locations')
    op.drop_table('cars')
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'mobile_number',
               existing_type=sa.VARCHAR(length=15),
               nullable=False)
    op.alter_column('users', 'postcode_of_home',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('users', 'city_of_home',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('users', 'address_of_home',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('users', 'last_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('users', 'first_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    # ### end Alembic commands ###
