"""add country

Revision ID: 2237c1d34f69
Revises: 316a87a8b13a
Create Date: 2025-08-17 14:54:47.305255

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2237c1d34f69'
down_revision = '316a87a8b13a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('charging_locations', sa.Column('country', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('country', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'country')
    op.drop_column('charging_locations', 'country')
    # ### end Alembic commands ###
