"""edit pricing

Revision ID: bb557dc9db1d
Revises: a42daa3ae731
Create Date: 2025-07-12 09:54:28.388224

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb557dc9db1d'
down_revision = 'a42daa3ae731'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pricing', sa.Column('price_per_kwh', sa.Float(), nullable=True))
    op.drop_column('pricing', 'price_per_khw')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pricing', sa.Column('price_per_khw', sa.FLOAT(), nullable=True))
    op.drop_column('pricing', 'price_per_kwh')
    # ### end Alembic commands ###
