"""modify charger location table

Revision ID: 85be4bd6e5a7
Revises: fd551f97f924
Create Date: 2025-07-22 23:22:13.505156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85be4bd6e5a7'
down_revision = 'fd551f97f924'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('charging_locations', sa.Column('latitude', sa.Text(), nullable=True))
    op.add_column('charging_locations', sa.Column('longitude', sa.Text(), nullable=True))
    op.drop_column('charging_locations', 'longtitude')
    op.drop_column('charging_locations', 'lattitude')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('charging_locations', sa.Column('lattitude', sa.TEXT(), nullable=True))
    op.add_column('charging_locations', sa.Column('longtitude', sa.TEXT(), nullable=True))
    op.drop_column('charging_locations', 'longitude')
    op.drop_column('charging_locations', 'latitude')
    # ### end Alembic commands ###
