"""add currency

Revision ID: a42daa3ae731
Revises: 19b8bdec6bc9
Create Date: 2025-07-12 09:06:06.511553

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a42daa3ae731'
down_revision = '19b8bdec6bc9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('charging_locations', sa.Column('currency', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('charging_locations', 'currency')
    # ### end Alembic commands ###
