"""remove activity

Revision ID: 3a1a21ff70cd
Revises: 6ff4d7363af8
Create Date: 2025-07-02 19:57:47.580358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a1a21ff70cd'
down_revision = '6ff4d7363af8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('activity')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity',
    sa.Column('activity_id', sa.INTEGER(), nullable=False),
    sa.Column('car_owner_user_id', sa.INTEGER(), nullable=True),
    sa.Column('charger_location_user_id', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('activity_id')
    )
    # ### end Alembic commands ###
