"""update location

Revision ID: c744e71b814f
Revises: f9df9fb9ff49
Create Date: 2025-06-30 23:52:10.253852

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c744e71b814f'
down_revision = 'f9df9fb9ff49'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pricing',
    sa.Column('pricing_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('currency', sa.Text(), nullable=True),
    sa.Column('total_value', sa.Float(), nullable=True),
    sa.Column('price_per_khw', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['booking.booking_id'], ),
    sa.PrimaryKeyConstraint('pricing_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pricing')
    # ### end Alembic commands ###
