"""update latitud

Revision ID: 316a87a8b13a
Revises: ddb295f437b0
Create Date: 2025-07-23 23:17:49.392095

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '316a87a8b13a'
down_revision = 'ddb295f437b0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
