"""update user

Revision ID: 19b8bdec6bc9
Revises: 29eefa075ae8
Create Date: 2025-07-09 09:30:15.320275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19b8bdec6bc9'
down_revision = '29eefa075ae8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_validated_email', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('is_validated_phone_number', sa.Boolean(), nullable=True))
    op.drop_column('users', 'is_validated')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_validated', sa.BOOLEAN(), nullable=True))
    op.drop_column('users', 'is_validated_phone_number')
    op.drop_column('users', 'is_validated_email')
    # ### end Alembic commands ###
