"""modify charger location table

Revision ID: ddb295f437b0
Revises: 85be4bd6e5a7
Create Date: 2025-07-22 23:28:30.250564

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ddb295f437b0'
down_revision = '85be4bd6e5a7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    try:
        op.drop_column('charging_locations', 'longitude')
    except Exception:
        pass

    try:
        op.drop_column('charging_locations', 'latitude')
    except Exception:
        pass
    op.add_column('charging_locations', sa.Column('latitude', sa.Numeric(10,7), nullable=True))
    op.add_column('charging_locations', sa.Column('longitude', sa.Numeric(10,7), nullable=True))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('charging_locations', 'longitude',
               existing_type=sa.Numeric(precision=10, scale=7),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('charging_locations', 'latitude',
               existing_type=sa.Numeric(precision=10, scale=7),
               type_=sa.TEXT(),
               existing_nullable=True)
    # ### end Alembic commands ###
