"""update location

Revision ID: 6ff4d7363af8
Revises: c744e71b814f
Create Date: 2025-07-01 22:52:32.969126

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ff4d7363af8'
down_revision = 'c744e71b814f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity',
    sa.Column('activity_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('car_owner_user_id', sa.Integer(), nullable=True),
    sa.Column('charger_location_user_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('activity_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('activity')
    # ### end Alembic commands ###
