"""add timestamp for email and phone

Revision ID: c4168d66a50d
Revises: bb557dc9db1d
Create Date: 2025-07-14 09:15:44.848529

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4168d66a50d'
down_revision = 'bb557dc9db1d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('expired_time_email_verification', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('expired_time_phone_verification', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'expired_time_phone_verification')
    op.drop_column('users', 'expired_time_email_verification')
    # ### end Alembic commands ###
