"""update user

Revision ID: 29eefa075ae8
Revises: 740ba91ef7dc
Create Date: 2025-07-04 18:02:41.915909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29eefa075ae8'
down_revision = '740ba91ef7dc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email_verification_code', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('phone_verification_code', sa.Text(), nullable=True))
    op.drop_column('users', 'phone_varification_code')
    op.drop_column('users', 'email_varification_code')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email_varification_code', sa.TEXT(), nullable=True))
    op.add_column('users', sa.Column('phone_varification_code', sa.TEXT(), nullable=True))
    op.drop_column('users', 'phone_verification_code')
    op.drop_column('users', 'email_verification_code')
    # ### end Alembic commands ###
