"""modify user table

Revision ID: d709069a8ea9
Revises: c4168d66a50d
Create Date: 2025-07-14 23:40:31.444064

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd709069a8ea9'
down_revision = 'c4168d66a50d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'user_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_type', sa.VARCHAR(length=20), nullable=False))
    # ### end Alembic commands ###
