"""modiy review table

Revision ID: 555c8956fb2f
Revises: 7f3c67c4d31c
Create Date: 2025-06-28 21:58:16.423743

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '555c8956fb2f'
down_revision = '7f3c67c4d31c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('booking')
    op.drop_table('notification')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('booking', 'end_time',
               existing_type=sa.DATETIME(),
               nullable=False)

    # ### end Alembic commands ###
