"""add review table

Revision ID: 77cbbb79d2cf
Revises: 89b0f3afaded
Create Date: 2025-06-26 15:55:22.164403

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77cbbb79d2cf'
down_revision = '89b0f3afaded'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booking', sa.Column('car_id', sa.Integer(), nullable=False))
    op.drop_constraint(None, 'booking', type_='foreignkey')
    op.create_foreign_key(None, 'booking', 'cars', ['car_id'], ['car_id'])
    op.drop_column('booking', 'user_id')
    op.alter_column('review', 'review_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('review', 'car_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('review', 'charging_location_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_foreign_key(None, 'review', 'charging_locations', ['charging_location_id'], ['charging_location_id'])
    op.create_foreign_key(None, 'review', 'cars', ['car_id'], ['car_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'review', type_='foreignkey')
    op.drop_constraint(None, 'review', type_='foreignkey')
    op.alter_column('review', 'charging_location_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('review', 'car_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('review', 'review_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.add_column('booking', sa.Column('user_id', sa.INTEGER(), nullable=False))
    op.drop_constraint(None, 'booking', type_='foreignkey')
    op.create_foreign_key(None, 'booking', 'users', ['user_id'], ['user_id'])
    op.drop_column('booking', 'car_id')
    # ### end Alembic commands ###
