"""add review table

Revision ID: 7f3c67c4d31c
Revises: 1a083d1e1960
Create Date: 2025-06-26 23:46:32.080847

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f3c67c4d31c'
down_revision = '1a083d1e1960'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('booking',
    sa.Column('booking_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('car_id', sa.Integer(), nullable=True),
    sa.Column('charging_location_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('review_rate', sa.Integer(), nullable=True),
    sa.Column('review_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['car_id'], ['cars.car_id'], ),
    sa.ForeignKeyConstraint(['charging_location_id'], ['charging_locations.charging_location_id'], ),
    sa.PrimaryKeyConstraint('booking_id')
    )
    op.create_table('review',
    sa.Column('review_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('review_rate', sa.Integer(), nullable=True),
    sa.Column('review_message', sa.Text(), nullable=True),
    sa.Column('car_id', sa.Integer(), nullable=False),
    sa.Column('charging_location_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['car_id'], ['cars.car_id'], ),
    sa.ForeignKeyConstraint(['charging_location_id'], ['charging_locations.charging_location_id'], ),
    sa.PrimaryKeyConstraint('review_id')
    )
    op.create_table('notification',
    sa.Column('notification_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('level', sa.Text(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['booking.booking_id'], ),
    sa.PrimaryKeyConstraint('notification_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notification')
    op.drop_table('review')
    op.drop_table('booking')
    # ### end Alembic commands ###
