"""correct booking table

Revision ID: 91d707b16289
Revises: 0677511dc2b9
Create Date: 2025-06-23 21:17:30.815215

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91d707b16289'
down_revision = '0677511dc2b9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('booking',
    sa.Column('booking_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('charging_location_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('review_rate', sa.Integer(), nullable=True),
    sa.Column('review_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['charging_location_id'], ['charging_locations.charging_location_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('booking_id')
    )
    op.drop_table('bookings')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookings',
    sa.Column('booking_id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('charging_location_id', sa.INTEGER(), nullable=False),
    sa.Column('start_time', sa.VARCHAR(length=50), nullable=False),
    sa.Column('end_time', sa.VARCHAR(length=50), nullable=False),
    sa.Column('review_rate', sa.INTEGER(), nullable=True),
    sa.Column('review_message', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['charging_location_id'], ['charging_locations.charging_location_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('booking_id')
    )
    op.drop_table('booking')
    # ### end Alembic commands ###
