"""add car and charging_location

Revision ID: b51b81b0bbbb
Revises: e6b567e45ce4
Create Date: 2025-05-25 11:37:02.843178

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b51b81b0bbbb'
down_revision = 'e6b567e45ce4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cars',
    sa.Column('car_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(length=50), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('color', sa.String(length=30), nullable=False),
    sa.Column('license_plate', sa.String(length=15), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('car_id'),
    sa.UniqueConstraint('license_plate')
    )
    op.create_table('charging_locations',
    sa.Column('charging_location_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('post_code', sa.String(length=20), nullable=False),
    sa.Column('alley', sa.String(length=100), nullable=False),
    sa.Column('street', sa.String(length=100), nullable=False),
    sa.Column('home_phone_number', sa.String(length=15), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('fast_charging', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('charging_location_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('charging_locations')
    op.drop_table('cars')
    # ### end Alembic commands ###
