"""Initial migration

Revision ID: e6b567e45ce4
Revises: 
Create Date: 2025-05-22 14:40:40.558898

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6b567e45ce4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('address_of_home', sa.Text(), nullable=False),
    sa.Column('city_of_home', sa.String(length=100), nullable=False),
    sa.Column('postcode_of_home', sa.String(length=20), nullable=False),
    sa.Column('user_type', sa.Enum('HOMEOWNER', 'ELECTRIC_CAR_OWNER', name='usertype'), nullable=False),
    sa.Column('mobile_number', sa.String(length=15), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
